so it seems that class files generated by Soot are in text-format while they should be in binary format .. that's why when Soot reads them back, it gets the magic number at the very beginning wrong (which is actually not there in the text-formatted file, along with other header information like min/maj version numbers, etc). I'll have to look into this a bit more.
Here's the error I get when I try to load one of those class files into Soot:

Creating output directories.
Loading properties.
Generating the call graph from Soot.
Adding archive: /u4/karim/workspace/cgc/dacapo/hsqldb.jar
Adding archive for resolving: /u4/karim/workspace/cgc/lib.jar
Adding archive: /u4/karim/workspace/cgc/dacapo/hsqldb-deps.jar
Wrong magic number in java.lang.NoClassDefFoundError: 779317109
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: Could not load classfile: java.lang.NoClassDefFoundError
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:194)
	at soot.SootResolver.bringToSignatures(SootResolver.java:219)
	at soot.SootResolver.bringToBodies(SootResolver.java:260)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:135)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:394)
	at soot.Scene.loadBasicClasses(Scene.java:959)
	at soot.Scene.loadNecessaryClasses(Scene.java:1018)
	at ca.uwaterloo.cgc.soot.CallGraphTransformer.getProbeCallGraph(CallGraphTransformer.java:134)
	at ca.uwaterloo.cgc.callgraph.CallGraphFactory.generateOriginalSparkCallGraph(CallGraphFactory.java:90)
	at ca.uwaterloo.cgc.OriginalSparkCallGraphGenerator.main(OriginalSparkCallGraphGenerator.java:16)
	... 5 more